### ISSUE TITLE
 ICDAR 2015 Text SR dataset

### ISSUE THREAD

**Issue by lingwei0816** [QaziSajid/Text-SRGAN#1]
Hello,thank you code for Text-SRAGN first.I wang to do some expriments on SR for OCR,and I cannot get access to the dataset in official website,Could you you share the dataset?Thank you very much!

**Comment by kaka0910** [comment]
Hello, I am sorry to bother you. Could you share the access to get the dataset？Thank you very much！

**Comment by QaziSajid** [comment]
I'm sorry, I cannot provide the dataset. It was given to me by my institution for purpose of this project, and I don't have permission to share it. Please follow the link in README and do the proper steps to get access to the dataset.

**Comment by kaka0910** [comment]
Thanks for your answer. By the way, are you trying to use this method for handwritten text images?

**Comment by lingwei0816** [comment]
OK,it doesn't matter.Thanks a lot.



---Original---

**Comment by QaziSajid** [comment]
@kaka0910 No, my project was limited to printed text. But I think it will work well on handwritten images too.

> Thanks for your answer. By the way, are you trying to use this method for handwritten text images?
